{% set name = "unsloth_zoo" %}
{% set version = "2025.12.7" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/unsloth_zoo-{{ version }}.tar.gz
  sha256: a610d611295e5f1ce199782540cd818c4a005ed235eff81a1728c5728d371452

build:
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - pytorch >=2.4.0
    - torchao >=0.13,!=0.14
    - triton
    - packaging >=24.1
    - tyro
    - transformers >=4.51.3,!=4.52.0,!=4.52.1,!=4.52.2,!=4.52.3z,!=4.53.0,!=4.54.0,!=4.55.0,!=4.55.1,<=4.56.2
    - datasets >=3.4.1,!=4.0.0,!=4.1.0,<4.4.0
    - sentencepiece >=0.2.0
    - tqdm
    - psutil
    - wheel >=0.42.0
    - numpy
    - accelerate >=0.34.1
    - trl >=0.7.9,!=0.9.0,!=0.9.1,!=0.9.2,!=0.9.3,!=0.15.0,!=0.19.0,<=0.23.0
    - peft >=0.7.1,!=0.11.0
    - protobuf
    - huggingface_hub >=0.34.0
    - hf-transfer
    - cut_cross_entropy
    - pillow
    - regex
    - msgspec
    - typing_extensions
    - filelock
    - mistral-common

test:
  # unsloth_zoo needs unsloth and vice-versa
  # imports:
  #  - unsloth_zoo
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}.*

about:
  home: https://github.com/unslothai/unsloth_zoo
  summary: Utils for Unsloth
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - isuruf
    - timkpaine
