{% set name = "unsloth_zoo" %}
{% set version = "2025.6.6" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/unsloth_zoo-{{ version }}.tar.gz
  sha256: 978f365eae950a019596a74c4359579236caf51a956f1e33607e2b8f671255a7

build:
  noarch: python
  script:
    - sed -i.bak "s/protobuf<4.0.0/protobuf/g" pyproject.toml
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - pytorch
    - triton
    - packaging
    - tyro
    - transformers >=4.46.1
    - datasets >=3.4.1
    - sentencepiece >=0.2.0
    - tqdm
    - psutil
    - wheel >=0.42.0
    - numpy
    - accelerate >=0.34.1
    - trl >=0.7.9,!=0.9.0,!=0.9.1,!=0.9.2,!=0.9.3,!=0.15.0
    - peft >=0.7.1,!=0.11.0
    - protobuf
    - huggingface_hub >=0.30.0
    - hf-transfer
    - cut_cross_entropy
    - pillow
    - regex
    - msgspec

test:
  # unsloth_zoo needs unsloth and vice-versa
  # imports:
  #  - unsloth_zoo
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}.*

about:
  home: https://github.com/unslothai/unsloth_zoo
  summary: Utils for Unsloth
  license: LGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - isuruf
    - timkpaine
